// The payment engine's schema, ported from the Flyway migrations of the three Java services.
// Kept as a TypeScript module rather than a .sql file so it needs no bundler loader and is
// guaranteed to be present at runtime on a serverless deployment.

export const SCHEMA_SQL = `
-- In the real system these tables live in three separate databases owned by three services that
-- can only talk over Kafka. Here they share one database because a serverless deployment has no
-- place to put three long-running processes. Everything that makes the design *correct* survives
-- the port, because it was never in the application layer to begin with: it is in the constraints
-- below. A bug in the handler code becomes a constraint violation, not silently corrupted money.
--
-- Every table is scoped by session_id. Each visitor gets an isolated world, so one person setting
-- the gateway to decline everything cannot break somebody else's payment, and the invariants are
-- a statement about one visitor's ledger rather than a sum over strangers.

CREATE TABLE IF NOT EXISTS sessions (
    id           UUID        PRIMARY KEY,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_seen_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------- the money

CREATE TABLE IF NOT EXISTS accounts (
    id             UUID         PRIMARY KEY,
    session_id     UUID         NOT NULL REFERENCES sessions (id) ON DELETE CASCADE,
    owner_id       VARCHAR(64)  NOT NULL,

    -- CUSTOMER accounts hold money and may never go negative.
    -- Exactly one SYSTEM account per session is where money ENTERS the ledger. In a closed
    -- double-entry system every credit needs a matching debit, so funding an account has to debit
    -- something; that something goes negative by construction and is a liability, not an
    -- overdraft. Without it, opening a funded account would be a credit with no counterpart and
    -- invariant I1 would break on the very first request.
    account_type   VARCHAR(10)  NOT NULL DEFAULT 'CUSTOMER',

    -- Money is a whole number of MINOR UNITS (paise). Never a float, never a double.
    currency       VARCHAR(3)   NOT NULL,
    balance_minor  BIGINT       NOT NULL,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT accounts_type_known
        CHECK (account_type IN ('CUSTOMER', 'SYSTEM', 'CLEARING')),

    -- Invariant I5, enforced by the database rather than hoped for by the service. Even a handler
    -- that skips its balance check cannot produce an overdraft: the UPDATE is rejected and the
    -- whole transaction rolls back. The SYSTEM account is exempt because its negative balance is
    -- the amount of money issued, which is exactly what it is supposed to record.
    CONSTRAINT accounts_customer_balance_non_negative
        CHECK (balance_minor >= 0 OR account_type = 'SYSTEM')
);

-- "Exactly one issuance account per session" as an index rather than a convention.
CREATE UNIQUE INDEX IF NOT EXISTS idx_accounts_single_system
    ON accounts (session_id) WHERE account_type = 'SYSTEM';

CREATE INDEX IF NOT EXISTS idx_accounts_session ON accounts (session_id);


CREATE TABLE IF NOT EXISTS ledger_entries (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id    UUID         NOT NULL REFERENCES sessions (id) ON DELETE CASCADE,
    transfer_id   UUID         NOT NULL,
    account_id    UUID         NOT NULL REFERENCES accounts (id) ON DELETE CASCADE,

    -- SIGNED. A debit is negative, a credit is positive, and the global sum is therefore 0.
    -- Storing an unsigned magnitude plus a type would make invariant I1 a CASE expression
    -- instead of a plain SUM(), and I1 should be impossible to write incorrectly.
    amount_minor  BIGINT       NOT NULL,
    entry_type    VARCHAR(6)   NOT NULL,
    currency      VARCHAR(3)   NOT NULL,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT ledger_entries_amount_non_zero
        CHECK (amount_minor <> 0),

    -- The sign IS the type. No code path can write a DEBIT that increases a balance.
    CONSTRAINT ledger_entries_sign_matches_type
        CHECK ((entry_type = 'DEBIT'  AND amount_minor < 0)
            OR (entry_type = 'CREDIT' AND amount_minor > 0)),

    -- The most important constraint in this file.
    --
    -- One transfer may post at most one DEBIT and one CREDIT per account. A retry or a duplicate
    -- delivery that tries to post the same leg twice hits a unique violation instead of creating
    -- money. Enforced by an index rather than a SELECT-then-INSERT check that would race.
    --
    -- It is also what makes completing and compensating one transfer mutually exclusive: a commit
    -- and a release write the IDENTICAL leg (transfer, clearing account, DEBIT), so the second one
    -- to arrive cannot be written at all.
    CONSTRAINT ledger_entries_one_leg_per_account_per_transfer
        UNIQUE (transfer_id, account_id, entry_type)
);

CREATE INDEX IF NOT EXISTS idx_ledger_entries_account ON ledger_entries (account_id);
CREATE INDEX IF NOT EXISTS idx_ledger_entries_session ON ledger_entries (session_id);


CREATE TABLE IF NOT EXISTS holds (
    id                  UUID         PRIMARY KEY,
    session_id          UUID         NOT NULL REFERENCES sessions (id) ON DELETE CASCADE,
    transfer_id         UUID         NOT NULL UNIQUE,
    from_account_id     UUID         NOT NULL REFERENCES accounts (id) ON DELETE CASCADE,
    to_account_id       UUID         NOT NULL REFERENCES accounts (id) ON DELETE CASCADE,
    clearing_account_id UUID         NOT NULL REFERENCES accounts (id) ON DELETE CASCADE,
    amount_minor        BIGINT       NOT NULL,
    currency            VARCHAR(3)   NOT NULL,
    status              VARCHAR(10)  NOT NULL,
    release_reason      VARCHAR(32),
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT holds_status_known CHECK (status IN ('ACTIVE', 'COMMITTED', 'RELEASED'))
);

-- A compensation that arrives before the step it compensates leaves a tombstone, so the two
-- commute whichever order they land in. Keyed by transfer, because the hold may not exist yet.
CREATE TABLE IF NOT EXISTS transfer_voids (
    transfer_id UUID         PRIMARY KEY,
    session_id  UUID         NOT NULL REFERENCES sessions (id) ON DELETE CASCADE,
    reason      VARCHAR(32)  NOT NULL,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- ------------------------------------------------------- the payment and its saga

CREATE TABLE IF NOT EXISTS transfers (
    id              UUID         PRIMARY KEY,
    session_id      UUID         NOT NULL REFERENCES sessions (id) ON DELETE CASCADE,
    from_account_id UUID         NOT NULL,
    to_account_id   UUID         NOT NULL,
    amount_minor    BIGINT       NOT NULL,
    currency        VARCHAR(3)   NOT NULL,
    status          VARCHAR(12)  NOT NULL,
    initiated_by    VARCHAR(64)  NOT NULL,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT transfers_amount_positive CHECK (amount_minor > 0),
    CONSTRAINT transfers_status_known
        CHECK (status IN ('PENDING', 'COMPLETED', 'COMPENSATED', 'FAILED'))
);

CREATE INDEX IF NOT EXISTS idx_transfers_session ON transfers (session_id, created_at DESC);


CREATE TABLE IF NOT EXISTS saga_instances (
    id            UUID         PRIMARY KEY,
    session_id    UUID         NOT NULL REFERENCES sessions (id) ON DELETE CASCADE,
    transfer_id   UUID         NOT NULL UNIQUE REFERENCES transfers (id) ON DELETE CASCADE,

    -- STARTED -> RESERVED -> CHARGED -> COMPLETED, with COMPENSATING -> COMPENSATED on a decline
    -- or a timeout before the pivot, and FAILED directly when the reserve is rejected.
    status        VARCHAR(14)  NOT NULL,
    hold_id       UUID,
    deadline_at   TIMESTAMPTZ  NOT NULL,
    completed_at  TIMESTAMPTZ,
    charge_sent   BOOLEAN      NOT NULL DEFAULT false,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT saga_status_known
        CHECK (status IN ('STARTED','RESERVED','CHARGED','COMPLETED','COMPENSATING','COMPENSATED','FAILED')),

    -- completed_at is set exactly when the status is terminal. The terminal set is written down
    -- here and in the invariant query, and the two must change together or I4 silently stops
    -- meaning anything.
    CONSTRAINT saga_completed_at_iff_terminal
        CHECK ((status IN ('COMPLETED','COMPENSATED','FAILED')) = (completed_at IS NOT NULL))
);

CREATE INDEX IF NOT EXISTS idx_saga_in_flight ON saga_instances (deadline_at)
    WHERE status NOT IN ('COMPLETED','COMPENSATED','FAILED');


-- One thing that happened to a saga. Append-only, like ledger_entries. Two rows per step: one
-- when the command is issued and one when its reply lands. A step with only the first row is a
-- step whose reply never came, which makes "where did this stall" a query rather than an
-- investigation.
CREATE TABLE IF NOT EXISTS saga_steps (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id  UUID         NOT NULL REFERENCES sessions (id) ON DELETE CASCADE,
    saga_id     UUID         NOT NULL,
    step_name   VARCHAR(48)  NOT NULL,
    outcome     VARCHAR(12)  NOT NULL,
    to_status   VARCHAR(14),
    message_id  UUID,
    detail      TEXT,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_saga_steps_saga ON saga_steps (saga_id, id);

-- ------------------------------------------------------------- idempotency

CREATE TABLE IF NOT EXISTS idempotency_records (
    id           BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id   UUID         NOT NULL REFERENCES sessions (id) ON DELETE CASCADE,
    idem_key     VARCHAR(128) NOT NULL,
    subject      VARCHAR(64)  NOT NULL,
    transfer_id  UUID,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),

    -- The whole gate. A duplicate arriving mid-flight BLOCKS on the uncommitted index tuple,
    -- then replays if the first committed and takes over if it rolled back.
    CONSTRAINT idempotency_unique_per_subject UNIQUE (session_id, subject, idem_key)
);

-- --------------------------------------------------- outbox, inbox, messages

-- A message is a row written in the SAME transaction as the state change it reports. The write
-- and the publish were never two operations that could disagree - that dual-write bug is the one
-- this whole design exists to avoid.
CREATE TABLE IF NOT EXISTS outbox (
    id           UUID         PRIMARY KEY,
    session_id   UUID         NOT NULL REFERENCES sessions (id) ON DELETE CASCADE,
    aggregate_id UUID         NOT NULL,
    topic        VARCHAR(64)  NOT NULL,
    event_type   VARCHAR(48)  NOT NULL,
    payload      JSONB        NOT NULL,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    published_at TIMESTAMPTZ,
    consumed_at  TIMESTAMPTZ,

    -- Set when a fault swallowed this message instead of delivering it. Kept rather than deleted,
    -- because "a message that was produced and never arrived" is the thing being demonstrated.
    dropped      BOOLEAN      NOT NULL DEFAULT false
);

CREATE INDEX IF NOT EXISTS idx_outbox_unpublished ON outbox (session_id, created_at)
    WHERE published_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_outbox_undelivered ON outbox (session_id, published_at)
    WHERE published_at IS NOT NULL AND consumed_at IS NULL;

-- Written inside the consumer's transaction, so "have I already handled this?" cannot race with
-- "do the work". A duplicate delivery collides here and is discarded before it can do anything.
CREATE TABLE IF NOT EXISTS inbox (
    message_id  UUID         PRIMARY KEY,
    session_id  UUID         NOT NULL REFERENCES sessions (id) ON DELETE CASCADE,
    event_type  VARCHAR(48)  NOT NULL,
    consumed_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- ------------------------------------------------------- the payment provider

CREATE TABLE IF NOT EXISTS gateway_charges (
    id           UUID         PRIMARY KEY,
    session_id   UUID         NOT NULL REFERENCES sessions (id) ON DELETE CASCADE,

    -- This UNIQUE is the mutual exclusion between a charge and its void: a void written with
    -- ON CONFLICT DO NOTHING blocks on a concurrent uncommitted charge and then sees it, so the
    -- void cannot lose the race.
    transfer_id  UUID         NOT NULL UNIQUE,
    amount_minor BIGINT       NOT NULL,
    status       VARCHAR(10)  NOT NULL,
    voided_at    TIMESTAMPTZ,
    void_reason  VARCHAR(32),
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT gateway_status_known CHECK (status IN ('APPROVED','DECLINED','VOIDED'))
);

-- Runtime-tunable failure injection, per session, exactly like the real gateway's /admin knobs.
CREATE TABLE IF NOT EXISTS faults (
    session_id       UUID        PRIMARY KEY REFERENCES sessions (id) ON DELETE CASCADE,
    gateway_mode     VARCHAR(16) NOT NULL DEFAULT 'APPROVE',
    duplicate_replies BOOLEAN    NOT NULL DEFAULT false,
    broker_down      BOOLEAN     NOT NULL DEFAULT false,
    drop_first_commit BOOLEAN    NOT NULL DEFAULT false,
    forward_recovery BOOLEAN     NOT NULL DEFAULT true,

    CONSTRAINT gateway_mode_known CHECK (gateway_mode IN ('APPROVE','DECLINE','TIMEOUT'))
);

-- Applied every boot. CREATE TABLE IF NOT EXISTS does nothing to a table that already exists, so
-- a column added after the first deploy needs saying separately.
ALTER TABLE outbox ADD COLUMN IF NOT EXISTS dropped BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE faults ADD COLUMN IF NOT EXISTS drop_first_commit BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE faults DROP COLUMN IF EXISTS drop_commit_reply;
`;
