-- M3: the saga.
--
-- This service stops being a passive projection of what account-service reports and becomes the
-- thing that DRIVES the flow: it issues commands, consumes replies, and decides at each step
-- whether to go forward or compensate.
--
-- Three tables, and they answer three different questions:
--
--   transfers        what did the caller ask for, and how did it end?    (the public answer)
--   saga_instances   where is this transfer RIGHT NOW?                   (the coordination state)
--   saga_steps       what has already been attempted, and when?          (the audit trail)
--
-- Plus this service's own outbox, because it now produces commands and needs the same
-- write-the-row-in-the-business-transaction guarantee account-service has had since M2.


-- =====================================================================================
-- transfers - the caller's view
-- =====================================================================================
--
-- Deliberately separate from saga_instances, even though there is exactly one saga per transfer
-- and the two could be one table.
--
-- They change for different reasons and are read by different people. `transfers` is the API
-- contract: it answers GET /transfers/{id} and its status vocabulary is the three words a caller
-- can act on. `saga_instances` is coordination machinery whose states exist to serve the
-- orchestrator's own restart and timeout logic - RESERVED and CHARGED mean nothing to a caller
-- and would be a breaking API change to remove. Merging them would leak the state machine into
-- the public contract and freeze it there.

CREATE TABLE transfers (
    -- Client-visible id, generated by this service when the request is accepted. It is also the
    -- saga's correlation key: it travels in every command and every reply, and it is what
    -- account-service stamps on its ledger entries and holds. One id spans three databases -
    -- which is what makes a stuck transfer traceable across all of them with one value.
    id               UUID         PRIMARY KEY,

    from_account_id  UUID         NOT NULL,
    to_account_id    UUID         NOT NULL,

    -- Minor units (paise), never a float. Same rule as the ledger.
    amount_minor     BIGINT       NOT NULL,
    currency         VARCHAR(3)   NOT NULL,

    -- Three words, on purpose.
    --
    -- FAILED covers both "the sender did not have the money" and "the gateway declined and we
    -- compensated". A caller cannot act differently on those two - their money is where it
    -- started either way - so distinguishing them in the public status would expose an internal
    -- distinction while buying nothing. The distinction IS kept, in saga_instances.status and in
    -- failure_reason below, for whoever is debugging.
    status           VARCHAR(9)   NOT NULL DEFAULT 'PENDING',

    -- Free text for a human, and NOT a machine contract - do not parse it. A stable machine
    -- readable code arrives with the error model in M4.
    failure_reason   TEXT,

    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT transfers_amount_positive CHECK (amount_minor > 0),
    CONSTRAINT transfers_status_known    CHECK (status IN ('PENDING', 'COMPLETED', 'FAILED')),

    -- A transfer to itself would make the saga lock the same account twice and post a debit and
    -- a credit that cancel. Rejected here as well as in the service, because a constraint cannot
    -- be forgotten by a new code path.
    CONSTRAINT transfers_distinct_accounts CHECK (from_account_id <> to_account_id)
);

CREATE INDEX idx_transfers_status ON transfers (status, created_at);


-- =====================================================================================
-- saga_instances - the coordination state
-- =====================================================================================
--
-- One row per running saga. This is the table invariant I4 is asserted against, and the table
-- the timeout sweeper scans.
--
-- THE STATES
--
--   STARTED             ReserveFunds emitted; waiting for account-service.
--   RESERVED            FundsReserved received, hold_id known; ChargeGateway emitted.
--   CHARGED             GatewayApproved received; CommitFunds emitted.
--   COMPLETED           FundsCommitted received. TERMINAL, happy path.
--   COMPENSATING        ReleaseFunds emitted, after a decline or a timeout.
--   COMPENSATED         FundsReleased received. TERMINAL, money returned to the sender.
--   FAILED              Reserve was rejected. TERMINAL, and note there is NOTHING to compensate -
--                       no money ever moved, so going through COMPENSATING would emit a release
--                       for a hold that does not exist.
--
-- Every state before a terminal one means a message is outstanding. That is exactly what
-- invariant I4 checks: after quiescence, a saga in a non-terminal state is a saga whose reply
-- never came, and somewhere there is a hold with money stranded in it.
--
-- WHY THE STATE IS A COLUMN AND NOT AN EVENT-SOURCED FOLD
--
-- The alternative is to keep only saga_steps and derive the state by replaying it. That is
-- purer, and it is worse here for one concrete reason: the timeout sweeper needs an indexed
-- query for "sagas past their deadline in a non-terminal state", and a derived state cannot be
-- indexed. The fold would have to run over every saga on every sweep. saga_steps keeps the full
-- history anyway, so nothing is lost - this column is a materialized view of it that the
-- sweeper can seek on.

CREATE TABLE saga_instances (
    id              UUID         PRIMARY KEY,

    -- UNIQUE, not just a reference: exactly one saga per transfer, ever. If a retry of the
    -- create-transfer path tried to start a second saga for the same transfer, both would
    -- reserve funds and the sender would be debited twice. That is prevented here by an index
    -- rather than by the service remembering to check.
    transfer_id     UUID         NOT NULL UNIQUE REFERENCES transfers (id),

    status          VARCHAR(12)  NOT NULL DEFAULT 'STARTED',

    -- Learned from FundsReserved, needed to address CommitFunds and ReleaseFunds at the right
    -- hold. NULL until the reserve replies - and a saga in COMPENSATING with a NULL hold_id is
    -- a bug, because there would be nothing to release.
    hold_id         UUID,

    -- The external PSP's reference, learned from GatewayApproved. Kept because a support ticket
    -- about a charge starts from this value, not from the transfer id.
    gateway_charge_id VARCHAR(64),

    -- THE COLUMN THAT MAKES THIS FAULT-TOLERANT RATHER THAN MERELY CORRECT.
    --
    -- If account-service dies after reserving and never replies, nothing else in this design
    -- will ever notice: Kafka has no "this reply is late" signal, and the orchestrator is not
    -- waiting on a thread it could time out. The saga simply sits in RESERVED forever with the
    -- sender's money in a hold. That is invariant I4 violated, and it is the failure a saga
    -- without timeouts always has - it just has not happened yet.
    --
    -- So every saga carries a wall-clock deadline from the moment it starts, and a scheduled
    -- sweeper drives anything past it into compensation. Set at insert time by the service, not
    -- by a DEFAULT here, because how long a step may take is policy and belongs in configuration
    -- where it can be tuned without a migration.
    deadline_at     TIMESTAMPTZ  NOT NULL,

    -- Diagnostics for the sweeper: which state was it stuck in, and how many times has the
    -- sweeper tried to unstick it. A saga the sweeper cannot finish is the DLQ conversation
    -- in M4.
    timed_out_at    TIMESTAMPTZ,
    sweep_attempts  INT          NOT NULL DEFAULT 0,

    failure_reason  TEXT,

    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    completed_at    TIMESTAMPTZ,

    CONSTRAINT saga_status_known CHECK (status IN (
        'STARTED', 'RESERVED', 'CHARGED', 'COMPLETED',
        'COMPENSATING', 'COMPENSATED', 'FAILED')),

    CONSTRAINT saga_sweep_attempts_non_negative CHECK (sweep_attempts >= 0),

    -- A terminal saga has finished; a running one has not. Keeping these two facts in lockstep
    -- means "when did this end" is answerable without inferring it from updated_at, which moves
    -- on every write.
    CONSTRAINT saga_completed_at_iff_terminal CHECK (
        (status IN ('COMPLETED', 'COMPENSATED', 'FAILED')) = (completed_at IS NOT NULL)
    ),

    -- Compensation releases a hold, so there has to be a hold to release. This catches the
    -- specific bug of routing a rejected reserve into COMPENSATING instead of FAILED - which
    -- would emit a ReleaseFunds naming a NULL hold and strand the saga on the reply.
    CONSTRAINT saga_compensation_needs_a_hold CHECK (
        status NOT IN ('COMPENSATING', 'COMPENSATED') OR hold_id IS NOT NULL
    )
);

-- The sweeper's query: non-terminal sagas whose deadline has passed. Partial, so the index
-- contains only sagas that are actually in flight - which on a healthy system is a handful of
-- rows regardless of how many millions have completed. A full index on (status, deadline_at)
-- would grow with the archive forever and the sweep would get slower every day.
CREATE INDEX idx_saga_instances_in_flight
    ON saga_instances (deadline_at)
    WHERE status NOT IN ('COMPLETED', 'COMPENSATED', 'FAILED');

-- Replies arrive carrying a transfer id, so this is the hot lookup on the consumer path.
-- Already served by the UNIQUE constraint on transfer_id.


-- =====================================================================================
-- saga_steps - the audit trail
-- =====================================================================================
--
-- Append-only, like ledger_entries and for the same reason: the value is in being able to
-- reconstruct exactly what happened and in what order, months later, from rows nobody edited.
--
-- This is what answers "why did transfer X compensate at 03:14" without reading a log
-- aggregator, and it is what makes the Grafana panel in M6 - step latency, compensation rate -
-- a database query rather than a metrics-cardinality problem.

CREATE TABLE saga_steps (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    saga_id       UUID         NOT NULL REFERENCES saga_instances (id),

    -- The command issued or the reply consumed, e.g. 'ReserveFunds', 'GatewayDeclined'. Free
    -- text rather than a CHECK constraint on purpose: adding a saga step should be a code change
    -- and a test, not a migration, and a typo here costs a confusing audit row rather than money.
    step_name     VARCHAR(64)  NOT NULL,

    -- STARTED when the command goes out, and a second row when the reply lands. Two rows rather
    -- than an UPDATE of one, because the table is append-only and because the gap between them
    -- IS the step latency.
    outcome       VARCHAR(12)  NOT NULL,

    -- The state the saga moved to as a result. Makes the transition sequence readable straight
    -- off this table, without joining anything.
    to_status     VARCHAR(12),

    -- The message id that caused this step, so a row here can be traced back to an outbox row in
    -- one database and an inbox row in another. This is the thread that stitches the three
    -- services' tables together during an incident.
    message_id    UUID,

    detail        TEXT,

    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT saga_steps_outcome_known
        CHECK (outcome IN ('STARTED', 'SUCCEEDED', 'FAILED', 'TIMED_OUT', 'SKIPPED'))
);

CREATE INDEX idx_saga_steps_saga ON saga_steps (saga_id, created_at);

COMMENT ON TABLE saga_steps IS
    'Append-only history of the saga. Never UPDATEd, never DELETEd. Two rows per step - one when '
    'the command is issued, one when its reply is consumed - so the elapsed time between them is '
    'the step latency, and a step with no second row is a step whose reply never came.';


-- =====================================================================================
-- outbox - identical in shape to account-service's V2__outbox.sql
-- =====================================================================================
--
-- This service now produces commands, so it needs the same guarantee: the command row and the
-- saga state change that decided to send it commit together, or neither does. Without it, the
-- orchestrator could move a saga to RESERVED and then fail to emit ChargeGateway - a saga that
-- believes it is waiting for a reply to a message that was never sent, which no retry recovers
-- and only the timeout sweeper would eventually notice.
--
-- The DDL is duplicated rather than shared because the table lives in a different database. The
-- CODE that drives it is shared, in common-messaging. See that module's POM for why the line is
-- drawn there.

CREATE TABLE outbox (
    id              UUID         PRIMARY KEY,
    aggregate_type  VARCHAR(64)  NOT NULL,
    aggregate_id    UUID         NOT NULL,
    topic           VARCHAR(128) NOT NULL,
    event_type      VARCHAR(64)  NOT NULL,
    payload         JSONB        NOT NULL,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    published_at    TIMESTAMPTZ,
    attempts        INT          NOT NULL DEFAULT 0,
    last_error      TEXT,

    CONSTRAINT outbox_attempts_non_negative CHECK (attempts >= 0)
);

-- Partial, matching the relay's ORDER BY so the claim is an index scan with no sort. See
-- account-service/V2__outbox.sql for the full reasoning.
CREATE INDEX idx_outbox_unpublished
    ON outbox (created_at, id) WHERE published_at IS NULL;

COMMENT ON TABLE outbox IS
    'Transactional outbox for the commands this orchestrator issues. Rows are inserted by the '
    'SAME transaction as the saga state change that decided to send them, and drained by '
    'OutboxRelay via FOR UPDATE SKIP LOCKED.';


-- The status vocabulary transfer_projection was given in M1 is now wrong: with the saga in
-- place a transfer can end FAILED, and the CHECK constraint would reject the row.
--
-- This projection is a leftover from M2, where it existed only to give the inbox a
-- non-idempotent side effect to protect. `transfers` is the real read model now. It is kept
-- because AccountEventConsumer still writes it and because apply_count is what proves the dedup
-- gate fires - but it is scheduled for deletion once M4's tests assert idempotency directly
-- against the saga.
ALTER TABLE transfer_projection DROP CONSTRAINT transfer_projection_status_known;
ALTER TABLE transfer_projection ADD CONSTRAINT transfer_projection_status_known
    CHECK (status IN ('COMPLETED', 'FAILED'));
