-- M1: the ledger core.
--
-- Two tables and nothing else. `holds` arrives in V2 with the saga (M3), because a hold is
-- meaningless until something exists that reserves funds and later commits or releases them.
--
-- Design note: correctness lives in constraints, not in application `if` statements. Every rule
-- below is enforced by Postgres, so a bug in the service layer becomes a constraint violation
-- rather than silently corrupted money. An application check has a race window; a constraint
-- does not.

CREATE TABLE accounts (
    id             UUID         PRIMARY KEY,

    -- The human/tenant this account belongs to. M5 checks it before letting anyone move money.
    owner_id       VARCHAR(64)  NOT NULL,

    -- CUSTOMER accounts hold money and may never go negative.
    --
    -- Exactly one SYSTEM account exists, and it is where money ENTERS the ledger. In a closed
    -- double-entry system every credit needs a matching debit, so funding a customer account
    -- has to debit something; that something goes negative by construction and is a liability,
    -- not an overdraft. Real ledgers call this the equity or issuance account. Without it,
    -- opening an account with a balance would be a credit with no counterpart - money created
    -- out of nothing, and invariant I1 broken on the very first request.
    account_type   VARCHAR(8)   NOT NULL DEFAULT 'CUSTOMER',

    -- VARCHAR, not CHAR(3): Postgres reports CHAR(n) as `bpchar`, which Hibernate's
    -- ddl-auto=validate does not accept for a String field. The boot would fail on a
    -- cosmetic type difference.
    currency       VARCHAR(3)   NOT NULL,

    -- Money is a whole number of MINOR UNITS (paise). Never a float, never a double.
    -- 300.00 INR is stored as 30000. See the denormalization note below.
    balance_minor  BIGINT       NOT NULL,

    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT accounts_type_known
        CHECK (account_type IN ('CUSTOMER', 'SYSTEM')),

    -- Invariant I5, enforced by the database rather than hoped for by the service.
    -- Even a service-layer bug that skips the balance check cannot produce an overdraft:
    -- the UPDATE is rejected and the whole transaction rolls back.
    --
    -- Read I5 precisely: "no CUSTOMER account balance < 0". The SYSTEM account is exempt
    -- because its negative balance is the amount of money issued into the ledger, which is
    -- exactly what it is supposed to record.
    CONSTRAINT accounts_customer_balance_non_negative
        CHECK (balance_minor >= 0 OR account_type = 'SYSTEM')
);

COMMENT ON COLUMN accounts.balance_minor IS
    'Denormalized cache of SUM(ledger_entries.amount_minor) for this account. Deliberate '
    'redundancy: you cannot row-lock a SUM(), and summing every entry per read does not scale. '
    'Written inside the SAME transaction as the entries. Invariant I2 asserts the two agree.';


CREATE TABLE ledger_entries (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Deliberately NOT a foreign key. `transfers` is owned by payment-orchestrator, in a
    -- different database. Referential integrity across a service boundary is exactly the
    -- coupling that database-per-service exists to prevent; the orchestrator's saga is what
    -- keeps the two consistent.
    transfer_id   UUID         NOT NULL,

    account_id    UUID         NOT NULL REFERENCES accounts (id),

    -- SIGNED. A debit is negative, a credit is positive, and the global sum is therefore 0.
    -- Storing an unsigned magnitude plus a type would make invariant I1 a CASE expression
    -- instead of a plain SUM(), and I1 should be impossible to write incorrectly.
    amount_minor  BIGINT       NOT NULL,

    entry_type    VARCHAR(6)   NOT NULL,
    currency      VARCHAR(3)   NOT NULL,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),

    -- A zero-amount entry is never meaningful and usually indicates a bug upstream.
    CONSTRAINT ledger_entries_amount_non_zero
        CHECK (amount_minor <> 0),

    -- The sign IS the type. Keeping them in lockstep means no code path can write a DEBIT
    -- that increases a balance.
    CONSTRAINT ledger_entries_sign_matches_type
        CHECK ((entry_type = 'DEBIT'  AND amount_minor < 0)
            OR (entry_type = 'CREDIT' AND amount_minor > 0)),

    -- The most important constraint in this file.
    --
    -- One transfer may post at most one DEBIT and one CREDIT per account. A retry, a duplicate
    -- Kafka delivery (M2), or a double-submitted request (M4) that tries to post the same leg
    -- twice hits a unique violation instead of creating money. This is the seed of idempotency,
    -- and it is enforced by an index rather than by a SELECT-then-INSERT check that would race.
    --
    -- Room is left for M3: a compensation writes the OPPOSITE type on the same
    -- (transfer_id, account_id), so the reversal is allowed exactly once and no more.
    CONSTRAINT ledger_entries_one_leg_per_account_per_transfer
        UNIQUE (transfer_id, account_id, entry_type)
);

-- Invariant I2 sums entries per account; without this it is a sequential scan per account.
-- (transfer_id is already indexed as the leading column of the UNIQUE constraint above.)
CREATE INDEX idx_ledger_entries_account_id ON ledger_entries (account_id);

COMMENT ON TABLE ledger_entries IS
    'Append-only. Never UPDATE, never DELETE. A mistake is corrected by writing an opposite '
    'entry - which is what a compensating transaction is at the data level. This table is '
    'therefore also a complete audit trail.';


-- Enforces "exactly one SYSTEM account" as an index rather than as a convention someone can
-- violate. Every matching row has the identical indexed value, so a second insert collides.
CREATE UNIQUE INDEX idx_accounts_single_system
    ON accounts (account_type) WHERE account_type = 'SYSTEM';

-- The issuance account, seeded with a well-known id so services and scripts can reference it
-- without a lookup. It starts at zero with no ledger entries, so invariants I1 and I2 both hold
-- on an empty database; it goes negative as customer accounts are funded.
INSERT INTO accounts (id, owner_id, account_type, currency, balance_minor)
VALUES ('00000000-0000-0000-0000-000000000001', 'system', 'SYSTEM', 'INR', 0);
