-- M2: the transactional outbox.
--
-- The problem this table solves: a business write goes to Postgres and a message goes to Kafka,
-- and there is no transaction that spans both. Whichever you do second can fail on its own,
-- leaving the ledger and the rest of the system disagreeing about what happened. Retrying does
-- not help - the crash can land between the two writes no matter how they are ordered.
--
-- The fix is to stop writing to two systems. The message becomes a ROW, inserted by the same
-- transaction that posts the ledger entries, so it is atomic with them by construction. A
-- separate relay process turns rows into Kafka records afterwards. One write, one system, ACID.
--
-- This table is therefore a queue that happens to live in the transactional store, and every
-- column below exists to make it a safe one.

CREATE TABLE outbox (
    -- Generated by the application, not by the database, and this is deliberate: the id must
    -- exist in Java before the INSERT so the same value can be put in the Kafka message.
    --
    -- This id is the system's message identity. It is what the consumer's inbox dedupes on, and
    -- it is stable across republishing: if the relay dies after the send but before marking the
    -- row published, the retry carries THIS id again, and the consumer recognises it. A Kafka
    -- offset would not have that property - the republished record gets a new one.
    id              UUID         PRIMARY KEY,

    -- What the message is about. Copied into the Kafka message KEY, which is what makes the
    -- ordering guarantee real: Kafka orders within a partition only, so keying by aggregate is
    -- what turns "unordered" into "ordered per transfer". Two messages about the same transfer
    -- cannot overtake each other; two messages about different transfers can, and consumers
    -- must be written to tolerate that.
    aggregate_type  VARCHAR(64)  NOT NULL,
    aggregate_id    UUID         NOT NULL,

    -- Routing is data, not code. The relay publishes whatever the row says, so adding a new
    -- message type never touches the relay.
    topic           VARCHAR(128) NOT NULL,
    event_type      VARCHAR(64)  NOT NULL,

    -- Serialized at WRITE time, inside the business transaction - not at publish time.
    -- If the relay serialized instead, a payload that fails to serialize would be discovered
    -- after the business transaction had already committed, and the message would be
    -- undeliverable with the money already moved. Failing inside the transaction rolls the
    -- whole thing back, which is the only safe direction to fail.
    payload         JSONB        NOT NULL,

    -- When the producing transaction committed. The relay's publish time is later by however
    -- long the poll interval and broker took; the difference is relay lag, which M6 graphs.
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),

    -- NULL means "not yet published". The relay's whole working set is the NULL rows.
    published_at    TIMESTAMPTZ,

    -- Diagnostics for a row the relay keeps failing to publish. A poison message that can never
    -- be sent will otherwise sit at the head of the queue invisibly; M4 turns a high attempt
    -- count into a DLQ decision.
    attempts        INT          NOT NULL DEFAULT 0,
    last_error      TEXT,

    CONSTRAINT outbox_attempts_non_negative CHECK (attempts >= 0)
);

-- A PARTIAL index, and the partial-ness is the point.
--
-- The relay only ever asks for unpublished rows, and after a busy day those are a vanishing
-- fraction of the table. A full index on (published_at, created_at) would grow with the
-- archive; this one grows only with the backlog, so the relay's query cost stays flat no matter
-- how many million messages have already been sent. Published rows are not in the index at all.
--
-- Column order matches the relay's ORDER BY so the claim query is an index scan with no sort.
CREATE INDEX idx_outbox_unpublished
    ON outbox (created_at, id) WHERE published_at IS NULL;

COMMENT ON TABLE outbox IS
    'Transactional outbox. Rows are inserted by the SAME transaction as the business write they '
    'describe, and drained by OutboxRelay via FOR UPDATE SKIP LOCKED. Published rows are kept as '
    'an audit trail until a retention job is added; the partial index means they cost the relay '
    'nothing while they sit here.';
